// Copyright Noah Games, Inc. All Rights Reserved.

#pragma once

#include "zencore.h"

#include <zencore/blake3.h>
#include <zencore/memory.h>

#include <string_view>

namespace zen {

class StringBuilderBase;

/**
 * Hash used for content addressable storage
 *
 * This is basically a BLAKE3-160 hash (note: this is probably not an officially
 * recognized identifier). It is generated by computing a 32-byte BLAKE3 hash and
 * picking the first 20 bytes of the resulting hash.
 *
 */
struct IoHash
{
	uint8_t Hash[20];

	static IoHash MakeFrom(const void* data /* 20 bytes */)
	{
		IoHash Io;
		memcpy(Io.Hash, data, sizeof Io);
		return Io;
	}

	static IoHash	   HashMemory(const void* data, size_t byteCount);
	static IoHash	   HashMemory(MemoryView Data) { return HashMemory(Data.GetData(), Data.GetSize()); }
	static IoHash	   FromHexString(const char* string);
	static IoHash	   FromHexString(const std::string_view string);
	const char*		   ToHexString(char* outString /* 40 characters + NUL terminator */) const;
	StringBuilderBase& ToHexString(StringBuilderBase& outBuilder) const;
	std::string		   ToHexString() const;

	static const int StringLength = 40;
	typedef char	 String_t[StringLength + 1];

	static IoHash Zero;	 // Initialized to all zeros

	inline auto operator<=>(const IoHash& rhs) const = default;

	struct Hasher
	{
		size_t operator()(const IoHash& v) const
		{
			size_t h;
			memcpy(&h, v.Hash, sizeof h);
			return h;
		}
	};
};

struct IoHashStream
{
	/// Begin streaming hash compute (not needed on freshly constructed instance)
	void Reset() { m_Blake3Stream.Reset(); }

	/// Append another chunk
	IoHashStream& Append(const void* data, size_t byteCount)
	{
		m_Blake3Stream.Append(data, byteCount);
		return *this;
	}

	/// Append another chunk
	IoHashStream& Append(MemoryView Data)
	{
		m_Blake3Stream.Append(Data.GetData(), Data.GetSize());
		return *this;
	}

	/// Obtain final hash. If you wish to reuse the instance call reset()
	IoHash GetHash()
	{
		BLAKE3 b3 = m_Blake3Stream.GetHash();

		IoHash Io;
		memcpy(Io.Hash, b3.Hash, sizeof Io.Hash);

		return Io;
	}

private:
	BLAKE3Stream m_Blake3Stream;
};

}  // namespace zen

